
package com.moon.jdk.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceServerImplService", targetNamespace = "http://server.jdk.moon.com/", wsdlLocation = "http://127.0.0.1:8888/WebService?wsdl")
public class WebServiceServerImplService
    extends Service
{

    private final static URL WEBSERVICESERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICESERVERIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICESERVERIMPLSERVICE_QNAME = new QName("http://server.jdk.moon.com/", "WebServiceServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESERVERIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICESERVERIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceServerImplService() {
        super(__getWsdlLocation(), WEBSERVICESERVERIMPLSERVICE_QNAME);
    }

    public WebServiceServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESERVERIMPLSERVICE_QNAME, features);
    }

    public WebServiceServerImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESERVERIMPLSERVICE_QNAME);
    }

    public WebServiceServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESERVERIMPLSERVICE_QNAME, features);
    }

    public WebServiceServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceServerImpl
     */
    @WebEndpoint(name = "WebServiceServerImplPort")
    public WebServiceServerImpl getWebServiceServerImplPort() {
        return super.getPort(new QName("http://server.jdk.moon.com/", "WebServiceServerImplPort"), WebServiceServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceServerImpl
     */
    @WebEndpoint(name = "WebServiceServerImplPort")
    public WebServiceServerImpl getWebServiceServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.jdk.moon.com/", "WebServiceServerImplPort"), WebServiceServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESERVERIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICESERVERIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICESERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
