package com.moon.cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-03T14:36:23.949+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "GreetingImplService", 
                  wsdlLocation = "http://localhost:8080/cfxWSServer/webservice/Greeting?wsdl",
                  targetNamespace = "http://server.cxfWebservice.moon.com/") 
public class GreetingImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.cxfWebservice.moon.com/", "GreetingImplService");
    public final static QName GreetingImplPort = new QName("http://server.cxfWebservice.moon.com/", "GreetingImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cfxWSServer/webservice/Greeting?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GreetingImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cfxWSServer/webservice/Greeting?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GreetingImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GreetingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreetingImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GreetingImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GreetingImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GreetingImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Greeting
     */
    @WebEndpoint(name = "GreetingImplPort")
    public Greeting getGreetingImplPort() {
        return super.getPort(GreetingImplPort, Greeting.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeting
     */
    @WebEndpoint(name = "GreetingImplPort")
    public Greeting getGreetingImplPort(WebServiceFeature... features) {
        return super.getPort(GreetingImplPort, Greeting.class, features);
    }

}
