package com.moon.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-03T14:36:23.944+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://server.cxfWebservice.moon.com/", name = "Greeting")
@XmlSeeAlso({ObjectFactory.class})
public interface Greeting {

    @WebMethod
    @RequestWrapper(localName = "greeting", targetNamespace = "http://server.cxfWebservice.moon.com/", className = "com.moon.cxf.client.Greeting_Type")
    @ResponseWrapper(localName = "greetingResponse", targetNamespace = "http://server.cxfWebservice.moon.com/", className = "com.moon.cxf.client.GreetingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String greeting(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
